import requests

def report_agent(state):
    prompt = f"""
    You are an expert radiologist.

    Based on the following reasoning:
    {state['reasoning']}

    Generate a structured chest X-ray report.

    Output STRICTLY in this format:

    FINDINGS:
    - ...

    IMPRESSION:
    - ...

    RECOMMENDATIONS:
    - ...
    """

    try:
        response = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": "llama3",
                "prompt": prompt,
                "stream": False
            }
        )

        data = response.json()

        # ✅ Handle errors safely
        if "error" in data:
            return {
                "report": f"LLM Error: {data['error']}"
            }

        report = data.get("response", "").strip()

        # ✅ Handle empty output
        if not report:
            report = "⚠️ Empty report generated by LLM"

        return {
            "report": report
        }

    except Exception as e:
        return {
            "report": f"Exception: {str(e)}"
        }